In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv('../datasets/NFL_schedule.csv')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2761 entries, 0 to 2760
Data columns (total 46 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   game_id           2761 non-null   str
 1   season            2761 non-null   int64
 2   game_type         2761 non-null   str
 3   week              2761 non-null   int64
 4   gameday           2761 non-null   str
 5   weekday           2761 non-null   str
 6   gametime          2761 non-null   str
 7   away_team         2761 non-null   str
 8   away_score        2761 non-null   int64
 9   home_team         2761 non-null   str
 10  home_score        2761 non-null   int64
 11  location          2761 non-null   str
 12  result            2761 non-null   int64
 13  total             2761 non-null   int64
 14  overtime          2761 non-null   int64
 15  old_game_id       2761 non-null   int64
 16  gsis              2761 non-null   int64
 17  nfl_detail_id     272 non-null    str
 18  pfr               2761 non-null   str
 19  pff               1894 non-null   float64
 20  espn              2761 non-null   int64
 21  ftn               1654 non-null   float64
 22  away_rest         2761 non-null   int64
 23  home_rest         2761 non-null   int64
 24  away_moneyline    2760 non-null   float64
 25  home_moneyline    2760 non-null   float64
 26  spread_line       2761 non-null   float64
 27  away_spread_odds  2760 non-null   float64
 28  home_spread_odds  2760 non-null   float64
 29  total_line        2761 non-null   float64
 30  under_odds        2760 non-null   float64
 31  over_odds         2760 non-null   float64
 32  div_game          2761 non-null   int64
 33  roof              2761 non-null   str
 34  surface           2717 non-null   str
 35  temp              1795 non-null   float64
 36  wind              1795 non-null   float64
 37  away_qb_id        2761 non-null   str
 38  home_qb_id        2761 non-null   str
 39  away_qb_name      2761 non-null   str
 40  home_qb_name      2761 non-null   str
 41  away_coach        2761 non-null   str
 42  home_coach        2761 non-null   str
 43  referee           2760 non-null   str
 44  stadium_id        2761 non-null   str
 45  stadium           2761 non-null   str
dtypes: float64(12), int64(13), str(21)
memory usage: 1.4 MB

In [5]:
df.columns

Index(['game_id', 'season', 'game_type', 'week', 'gameday', 'weekday',
       'gametime', 'away_team', 'away_score', 'home_team', 'home_score',
       'location', 'result', 'total', 'overtime', 'old_game_id', 'gsis',
       'nfl_detail_id', 'pfr', 'pff', 'espn', 'ftn', 'away_rest', 'home_rest',
       'away_moneyline', 'home_moneyline', 'spread_line', 'away_spread_odds',
       'home_spread_odds', 'total_line', 'under_odds', 'over_odds', 'div_game',
       'roof', 'surface', 'temp', 'wind', 'away_qb_id', 'home_qb_id',
       'away_qb_name', 'home_qb_name', 'away_coach', 'home_coach', 'referee',
       'stadium_id', 'stadium'],
      dtype='str')

In [6]:
df['div_game'].unique()

array([0, 1])

In [7]:
df['winner (home)'] = (df['home_score'] > df['away_score']).astype(int)

In [8]:
pd.set_option('display.max_columns', None)
df.tail(1)

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,home_score,location,result,total,overtime,old_game_id,gsis,nfl_detail_id,pfr,pff,espn,ftn,away_rest,home_rest,away_moneyline,home_moneyline,spread_line,away_spread_odds,home_spread_odds,total_line,under_odds,over_odds,div_game,roof,surface,temp,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium,winner (home)
2760,2025_22_SEA_NE,2025,SB,22,2026-02-08,Sunday,18:30,SEA,29,NE,13,Neutral,-16,42,0,2026020800,60176,NaN,202602080nwe,NaN,401772988,NaN,14,14,-238.0,195.0,-4.5,-115.0,-105.0,45.5,-115.0,-105.0,0,outdoors,grass,67.0,7.0,00-0034869,00-0039851,Sam Darnold,Drake Maye,Mike Macdonald,Mike Vrabel,Shawn Smith,SFO01,Levi's Stadium,0

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
X_pred = df[['season', 'week', 'game_type', 'away_team', 'home_team', 'away_rest', 'home_rest', 'spread_line', 'away_spread_odds', 'home_spread_odds', 'total_line', 'div_game']]
X_pred = pd.get_dummies(data=X_pred, columns=['game_type', 'away_team', 'home_team'], drop_first=True, dtype=int)
X_pred.tail(1)

,season,week,away_rest,home_rest,spread_line,away_spread_odds,home_spread_odds,total_line,div_game,game_type_DIV,game_type_REG,game_type_SB,game_type_WC,away_team_ATL,away_team_BAL,away_team_BUF,away_team_CAR,away_team_CHI,away_team_CIN,away_team_CLE,away_team_DAL,away_team_DEN,away_team_DET,away_team_GB,away_team_HOU,away_team_IND,away_team_JAX,away_team_KC,away_team_LA,away_team_LAC,away_team_LV,away_team_MIA,away_team_MIN,away_team_NE,away_team_NO,away_team_NYG,away_team_NYJ,away_team_OAK,away_team_PHI,away_team_PIT,away_team_SD,away_team_SEA,away_team_SF,away_team_TB,away_team_TEN,away_team_WAS,home_team_ATL,home_team_BAL,home_team_BUF,home_team_CAR,home_team_CHI,home_team_CIN,home_team_CLE,home_team_DAL,home_team_DEN,home_team_DET,home_team_GB,home_team_HOU,home_team_IND,home_team_JAX,home_team_KC,home_team_LA,home_team_LAC,home_team_LV,home_team_MIA,home_team_MIN,home_team_NE,home_team_NO,home_team_NYG,home_team_NYJ,home_team_OAK,home_team_PHI,home_team_PIT,home_team_SD,home_team_SEA,home_team_SF,home_team_TB,home_team_TEN,home_team_WAS
2760,2025,22,14,14,-4.5,-115.0,-105.0,45.5,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [14]:
y = df['winner (home)']

In [15]:
X_pred.info()

<class 'pandas.DataFrame'>
RangeIndex: 2761 entries, 0 to 2760
Data columns (total 79 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   season            2761 non-null   int64
 1   week              2761 non-null   int64
 2   away_rest         2761 non-null   int64
 3   home_rest         2761 non-null   int64
 4   spread_line       2761 non-null   float64
 5   away_spread_odds  2760 non-null   float64
 6   home_spread_odds  2760 non-null   float64
 7   total_line        2761 non-null   float64
 8   div_game          2761 non-null   int64
 9   game_type_DIV     2761 non-null   int64
 10  game_type_REG     2761 non-null   int64
 11  game_type_SB      2761 non-null   int64
 12  game_type_WC      2761 non-null   int64
 13  away_team_ATL     2761 non-null   int64
 14  away_team_BAL     2761 non-null   int64
 15  away_team_BUF     2761 non-null   int64
 16  away_team_CAR     2761 non-null   int64
 17  away_team_CHI     2761 non-null   int64
 18  away_team_CIN     2761 non-null   int64
 19  away_team_CLE     2761 non-null   int64
 20  away_team_DAL     2761 non-null   int64
 21  away_team_DEN     2761 non-null   int64
 22  away_team_DET     2761 non-null   int64
 23  away_team_GB      2761 non-null   int64
 24  away_team_HOU     2761 non-null   int64
 25  away_team_IND     2761 non-null   int64
 26  away_team_JAX     2761 non-null   int64
 27  away_team_KC      2761 non-null   int64
 28  away_team_LA      2761 non-null   int64
 29  away_team_LAC     2761 non-null   int64
 30  away_team_LV      2761 non-null   int64
 31  away_team_MIA     2761 non-null   int64
 32  away_team_MIN     2761 non-null   int64
 33  away_team_NE      2761 non-null   int64
 34  away_team_NO      2761 non-null   int64
 35  away_team_NYG     2761 non-null   int64
 36  away_team_NYJ     2761 non-null   int64
 37  away_team_OAK     2761 non-null   int64
 38  away_team_PHI     2761 non-null   int64
 39  away_team_PIT     2761 non-null   int64
 40  away_team_SD      2761 non-null   int64
 41  away_team_SEA     2761 non-null   int64
 42  away_team_SF      2761 non-null   int64
 43  away_team_TB      2761 non-null   int64
 44  away_team_TEN     2761 non-null   int64
 45  away_team_WAS     2761 non-null   int64
 46  home_team_ATL     2761 non-null   int64
 47  home_team_BAL     2761 non-null   int64
 48  home_team_BUF     2761 non-null   int64
 49  home_team_CAR     2761 non-null   int64
 50  home_team_CHI     2761 non-null   int64
 51  home_team_CIN     2761 non-null   int64
 52  home_team_CLE     2761 non-null   int64
 53  home_team_DAL     2761 non-null   int64
 54  home_team_DEN     2761 non-null   int64
 55  home_team_DET     2761 non-null   int64
 56  home_team_GB      2761 non-null   int64
 57  home_team_HOU     2761 non-null   int64
 58  home_team_IND     2761 non-null   int64
 59  home_team_JAX     2761 non-null   int64
 60  home_team_KC      2761 non-null   int64
 61  home_team_LA      2761 non-null   int64
 62  home_team_LAC     2761 non-null   int64
 63  home_team_LV      2761 non-null   int64
 64  home_team_MIA     2761 non-null   int64
 65  home_team_MIN     2761 non-null   int64
 66  home_team_NE      2761 non-null   int64
 67  home_team_NO      2761 non-null   int64
 68  home_team_NYG     2761 non-null   int64
 69  home_team_NYJ     2761 non-null   int64
 70  home_team_OAK     2761 non-null   int64
 71  home_team_PHI     2761 non-null   int64
 72  home_team_PIT     2761 non-null   int64
 73  home_team_SD      2761 non-null   int64
 74  home_team_SEA     2761 non-null   int64
 75  home_team_SF      2761 non-null   int64
 76  home_team_TB      2761 non-null   int64
 77  home_team_TEN     2761 non-null   int64
 78  home_team_WAS     2761 non-null   int64
dtypes: float64(4), int64(75)
memory usage: 1.7 MB

In [16]:
X_pred = X_pred.fillna(X_pred.median(numeric_only=True))

In [ ]:
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(
    X_pred, y, test_size=0.2, random_state=42, stratify=y
)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression(max_iter=2000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)[:, 1]

model_scaled = LogisticRegression(max_iter=2000)
model_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = model_scaled.predict(X_test_scaled)
y_scaled_proba = model_scaled.predict_proba(X_test_scaled)[:, 1]


print(f"ROC_AUC: {roc_auc_score(y_test, y_pred_proba)}")
print(f"Accuracy without scaling:  {accuracy_score(y_test, y_pred)}")
print(f"Confusion Matrix without scaling: {confusion_matrix(y_test, y_pred)}")

print(f"ROC_AUC_scaled: {roc_auc_score(y_test, y_scaled_proba)}")
print(f"Accuracy with scaling:  {accuracy_score(y_test, y_pred_scaled)}")
print(f"Confusion Matrix with scaling: {confusion_matrix(y_test, y_pred_scaled)}")

ROC_AUC: 0.6973597359735972
Accuracy without scaling:  0.6455696202531646
Confusion Matrix without scaling: [[137 113]
 [ 83 220]]
ROC_AUC_scaled: 0.6911287128712871
Accuracy with scaling:  0.6419529837251357
Confusion Matrix with scaling: [[135 115]
 [ 83 220]]

c:\Yaroslav Skuratovich folder\NFL_prediction\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [20]:
!pip install optuna

Collecting optuna
  Using cached optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.19.1-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Using cached colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in C:\Yaroslav Skuratovich folder\NFL_prediction\.venv\Lib\site-packages (from optuna) (2.5.2)
Requirement already satisfied: packaging>=20.0 in C:\Yaroslav Skuratovich folder\NFL_prediction\.venv\Lib\site-packages (from optuna) (26.3)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Downloading sqlalchemy-2.0.52-cp313-cp313-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: tqdm in C:\Yaroslav Skuratovich folder\NFL_prediction\.venv\Lib\site-packages (from optuna) (4.70.0)
Collecting PyYAML (from optuna)
  Using cached pyyaml-6.0.3-cp313-cp313-win_amd64.whl.metadata (2.4 kB)
Collecting Mako (from alembic>=1.5.0->optuna)
  Using cached mako-1.4.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in C:\Yaroslav Skuratovich folder\NFL_prediction\.venv\Lib\site-packages (from alembic>=1.5.0->optuna) (4.16.0)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna)
  Downloading greenlet-3.5.5-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: colorama in C:\Yaroslav Skuratovich folder\NFL_prediction\.venv\Lib\site-packages (from colorlog->optuna) (0.4.6)
Collecting MarkupSafe>=2.0 (from Mako->alembic>=1.5.0->optuna)
  Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Using cached optuna-4.9.0-py3-none-any.whl (425 kB)
Downloading alembic-1.19.1-py3-none-any.whl (265 kB)
Downloading sqlalchemy-2.0.52-cp313-cp313-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   -------------------------------------- - 2.1/2.2 MB 14.6 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 11.7 MB/s  0:00:00
Downloading greenlet-3.5.5-cp313-cp313-win_amd64.whl (324 kB)
Using cached colorlog-6.12.0-py3-none-any.whl (12 kB)
Using cached mako-1.4.1-py3-none-any.whl (80 kB)
Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl (15 kB)
Using cached pyyaml-6.0.3-cp313-cp313-win_amd64.whl (154 kB)
Installing collected packages: PyYAML, MarkupSafe, greenlet, colorlog, sqlalchemy, Mako, alembic, optuna

   ---------------------------------------- 0/8 [PyYAML]
   ---------------------------------------- 0/8 [PyYAML]
   ---------- ----------------------------- 2/8 [greenlet]
   ---------- ----------------------------- 2/8 [greenlet]
   ---------- ----------------------------- 2/8 [greenlet]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   -------------------- ------------------- 4/8 [sqlalchemy]
   ------------------------- -------------- 5/8 [Mako]
   ------------------------- -------------- 5/8 [Mako]
   ------------------------- -------------- 5/8 [Mako]
   ------------------------- -------------- 5/8 [Mako]
   ------------------------------ --------- 6/8 [alembic]
   ------------------------------ --------- 6/8 [alembic]
   ------------------------------ --------- 6/8 [alembic]
   ------------------------------ --------- 6/8 [alembic]
   ------------------------------ --------- 6/8 [alembic]
   ------------------------------ --------- 6/8 [alembic]
   ------------------------------ --------- 6/8 [alembic]
   ------------------------------ --------- 6/8 [alembic]
   ------------------------------ --------- 6/8 [alembic]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ----------------------------------- ---- 7/8 [optuna]
   ---------------------------------------- 8/8 [optuna]

Successfully installed Mako-1.4.1 MarkupSafe-3.0.3 PyYAML-6.0.3 alembic-1.19.1 colorlog-6.12.0 greenlet-3.5.5 optuna-4.9.0 sqlalchemy-2.0.52

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
import optuna
from sklearn.model_selection import cross_val_score

def objective(trial):
    params = {
        'penalty' :trial.suggest_categorical('penalty', ['l1', 'l2', 'elasticnet', None]),
        'C' : trial.suggest_float('C', 1e-4, 1e3, log=True),  
    }
    
    if params['penalty'] == 'elasticnet':
        params['l1_ratio'] = trial.suggest_float('l1_ratio', 0.0, 1.0)
    
    model = LogisticRegression(**params, solver='saga', max_iter=2000, random_state=101)
    score = cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy', n_jobs=-1)
    return score.mean()
    

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)
print(study.best_value)
print(study.best_params)

[I 2026-08-18 21:20:59,243] A new study created in memory with name: no-name-c606098b-b39f-4e78-9237-2dcd0f486b14
[I 2026-08-18 21:21:02,258] Trial 0 finished with value: 0.5915012158709637 and parameters: {'penalty': 'l1', 'C': 0.0006081720984060961}. Best is trial 0 with value: 0.5915012158709637.
[I 2026-08-18 21:21:04,883] Trial 1 finished with value: 0.6675593314248777 and parameters: {'penalty': 'l1', 'C': 0.060645491527453625}. Best is trial 1 with value: 0.6675593314248777.
[I 2026-08-18 21:21:07,553] Trial 2 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l2', 'C': 45.20856775014501}. Best is trial 1 with value: 0.6675593314248777.
[I 2026-08-18 21:21:09,838] Trial 3 finished with value: 0.6666533279978658 and parameters: {'penalty': None, 'C': 0.00042134867165952866}. Best is trial 1 with value: 0.6675593314248777.
[I 2026-08-18 21:21:10,981] Trial 4 finished with value: 0.6680118201126605 and parameters: {'penalty': 'elasticnet', 'C': 0.06685155169782453, 'l1_ratio': 0.8755221658211406}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:12,228] Trial 5 finished with value: 0.6666533279978658 and parameters: {'penalty': 'elasticnet', 'C': 3.58204768721155, 'l1_ratio': 0.5857086025685772}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:13,079] Trial 6 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l2', 'C': 164.49205103134432}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:13,155] Trial 7 finished with value: 0.5484604098049476 and parameters: {'penalty': 'l1', 'C': 0.00022195355020402746}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:14,142] Trial 8 finished with value: 0.666200839310083 and parameters: {'penalty': 'elasticnet', 'C': 0.002293743695779865, 'l1_ratio': 0.7117985429373053}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:15,211] Trial 9 finished with value: 0.6652948358830713 and parameters: {'penalty': 'elasticnet', 'C': 0.0015696688499364047, 'l1_ratio': 0.10126672706325879}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:16,093] Trial 10 finished with value: 0.6666533279978658 and parameters: {'penalty': None, 'C': 0.2422851572376138}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:17,302] Trial 11 finished with value: 0.6675593314248777 and parameters: {'penalty': 'l1', 'C': 0.06472620490467637}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:18,384] Trial 12 finished with value: 0.6671068427370949 and parameters: {'penalty': 'l1', 'C': 0.050066162749029065}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:19,597] Trial 13 finished with value: 0.6666533279978658 and parameters: {'penalty': 'elasticnet', 'C': 1.4285787812551662, 'l1_ratio': 0.9636750016719927}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:20,772] Trial 14 finished with value: 0.6671058166856486 and parameters: {'penalty': 'elasticnet', 'C': 0.016427557440647743, 'l1_ratio': 0.06585356511039264}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:21,966] Trial 15 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l1', 'C': 1.1193870760179014}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:22,818] Trial 16 finished with value: 0.6666533279978658 and parameters: {'penalty': None, 'C': 0.01052368442606196}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:23,671] Trial 17 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l2', 'C': 18.58562962591926}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:24,814] Trial 18 finished with value: 0.6666533279978658 and parameters: {'penalty': 'elasticnet', 'C': 0.24105412562049847, 'l1_ratio': 0.49421342969718635}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:25,955] Trial 19 finished with value: 0.666200839310083 and parameters: {'penalty': 'l1', 'C': 0.0054515885643555}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:27,077] Trial 20 finished with value: 0.6675593314248777 and parameters: {'penalty': 'l1', 'C': 0.10620968161565668}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:28,147] Trial 21 finished with value: 0.6662018653615293 and parameters: {'penalty': 'l1', 'C': 0.035028201631842185}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:29,350] Trial 22 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l1', 'C': 0.5196815602408916}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:30,624] Trial 23 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l1', 'C': 5.68910353004106}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:31,828] Trial 24 finished with value: 0.6675593314248777 and parameters: {'penalty': 'l1', 'C': 0.11306222891098314}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:32,900] Trial 25 finished with value: 0.6671068427370949 and parameters: {'penalty': 'elasticnet', 'C': 0.04636542212250996, 'l1_ratio': 0.9862733373487814}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:33,858] Trial 26 finished with value: 0.6666533279978658 and parameters: {'penalty': None, 'C': 681.7355174647075}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:34,742] Trial 27 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l2', 'C': 0.007657227217209208}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:35,730] Trial 28 finished with value: 0.666200839310083 and parameters: {'penalty': 'l1', 'C': 0.0025874546724641927}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:36,944] Trial 29 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l1', 'C': 0.4663703327457349}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:37,026] Trial 30 finished with value: 0.5466504550538164 and parameters: {'penalty': 'elasticnet', 'C': 0.00010741783713547221, 'l1_ratio': 0.3761568307241237}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:38,180] Trial 31 finished with value: 0.6680118201126605 and parameters: {'penalty': 'l1', 'C': 0.0990120658018928}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:39,252] Trial 32 finished with value: 0.6666564061522045 and parameters: {'penalty': 'l1', 'C': 0.02121827035367401}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:40,382] Trial 33 finished with value: 0.6680118201126605 and parameters: {'penalty': 'l1', 'C': 0.08852988007904496}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:41,606] Trial 34 finished with value: 0.6671058166856486 and parameters: {'penalty': 'l1', 'C': 0.16112268278378847}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:42,502] Trial 35 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l2', 'C': 2.361564641202109}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:43,737] Trial 36 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l1', 'C': 0.4378201081148802}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:44,623] Trial 37 finished with value: 0.6666533279978658 and parameters: {'penalty': None, 'C': 0.027632081865529807}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:45,613] Trial 38 finished with value: 0.6657473245708541 and parameters: {'penalty': 'elasticnet', 'C': 0.0013719310855504516, 'l1_ratio': 0.3012329568720916}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:46,529] Trial 39 finished with value: 0.5765516462995455 and parameters: {'penalty': 'l1', 'C': 0.0005768511251334661}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:47,455] Trial 40 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l2', 'C': 6.259819387377999}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:48,568] Trial 41 finished with value: 0.6680118201126605 and parameters: {'penalty': 'l1', 'C': 0.09398079978226008}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:49,710] Trial 42 finished with value: 0.6680118201126605 and parameters: {'penalty': 'l1', 'C': 0.09043571384474898}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:50,904] Trial 43 finished with value: 0.6680118201126605 and parameters: {'penalty': 'l1', 'C': 0.0890239680864995}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:52,150] Trial 44 finished with value: 0.6666533279978658 and parameters: {'penalty': 'l1', 'C': 0.6546964796409462}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:53,149] Trial 45 finished with value: 0.665293809831625 and parameters: {'penalty': 'l1', 'C': 0.004815494825913912}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:54,282] Trial 46 finished with value: 0.6666533279978658 and parameters: {'penalty': 'elasticnet', 'C': 0.23069694714584346, 'l1_ratio': 0.7859333653099246}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:55,373] Trial 47 finished with value: 0.665293809831625 and parameters: {'penalty': 'l1', 'C': 0.010723656426129102}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:56,487] Trial 48 finished with value: 0.6671068427370949 and parameters: {'penalty': 'l1', 'C': 0.05474865666734114}. Best is trial 4 with value: 0.6680118201126605.
[I 2026-08-18 21:21:57,476] Trial 49 finished with value: 0.6666533279978658 and parameters: {'penalty': None, 'C': 1.155121879479113}. Best is trial 4 with value: 0.6680118201126605.

0.6680118201126605
{'penalty': 'elasticnet', 'C': 0.06685155169782453, 'l1_ratio': 0.8755221658211406}

In [27]:
best_parms = study.best_params
final_model = LogisticRegression(**best_parms, solver='saga', max_iter=2000, random_state=101)
final_model.fit(X_train, y_train)
y_pred_final = final_model.predict(X_test)
y_pred_final_proba = final_model.predict_proba(X_test)[:, 1]
print(f"ROC_AUC: {roc_auc_score(y_test, y_pred_final_proba)}")
print(f"Accuracy:  {accuracy_score(y_test, y_pred_final)}")
print(f"Confusion Matrix without scaling: {confusion_matrix(y_test, y_pred_final)}")

c:\Yaroslav Skuratovich folder\NFL_prediction\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

ROC_AUC: 0.7203564356435643
Accuracy:  0.6672694394213382
Confusion Matrix without scaling: [[136 114]
 [ 70 233]]